# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://archdron.github.io"

enableRobotsTXT = false
paginate = 10
summaryLength = 0
colorScheme = "congo"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[languages]
  [langages.en]
    [languages.en.params]
      languageCode="en"
      languageName = "English"
      languageDirection = 'ltr'
      displayName = "EN"
      weight = 1
      isoCode = "en"
      dateFormat = "Jan 2, 2006"
      disabled = false
      title = "Andrii Serbovets"
      description = "Translating, editing, localizing games and stuff"
      copyright = "¬© Andrii Serbovets"
    [languages.en.author]
      image = "img/author.jpg"
      name = "Andrii Serbovets"
      headline = "Overthinking translation, editing, proofreading, and localization ü§î"
      links = [
        { linkedin = "https://linkedin.com/in/aserbovets" },
        { mastodon = "https://mastodon.online/@archdron" },
        { medium = "https://medium.com/@archdron" },
        { telegram = "https://t.me/aserbovets" },
      ]
      
  [languages.uk]
    [languages.uk.params]
      languageCode = "uk"
      languageName = "–£–∫—Ä–∞—ó–Ω—Å—å–∫–∞"
      languageDirection = 'ltr'
      displayName = "–£–ö–†"
      isoCode = "uk"
      weight = 2
      rtl = false
      dateFormat = "2 –∂–æ–≤—Ç–Ω—è 2006 —Ä."
      disabled = false
      title = "–ê–Ω–¥—Ä—ñ–π –°–µ—Ä–±–æ–≤–µ—Ü—å"
      description = "–ü–µ—Ä–µ–∫–ª–∞–¥–∞—é, —Ä–µ–¥–∞–≥—É—é, –ª–æ–∫–∞–ª—ñ–∑—É—é —É—Å—è–∫—É –≤—Å—è—á–∏–Ω—É"
      copyright = "¬© –°–µ—Ä–±–æ–≤–µ—Ü—å –ê. –ê."
    [languages.uk.author]
      image = "img/author.jpg"
      name = "–ê–Ω–¥—Ä—ñ–π –°–µ—Ä–±–æ–≤–µ—Ü—å"
      headline = "–ù–∞–¥—Ç–æ –ø–µ—Ä–µ–π–º–∞—é—Å—è –ø–µ—Ä–µ–∫–ª–∞–¥–∞–º–∏, —Ä–µ–¥–∞–≥—É–≤–∞–Ω–Ω—è–º, —ñ –ª–æ–∫–∞–ª—ñ–∑–∞—Ü—ñ—î—é ü§î"
      links = [
        { linkedin = "https://linkedin.com/in/aserbovets" },
        { mastodon = "https://mastodon.online/@archdron" },
        { medium = "https://medium.com/@archdron" },
        { telegram = "https://t.me/aserbovets" },
      ]
